---
apiVersion: v1
kind: Namespace
metadata:
  name: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: controller
---
{{- $root := . -}}
{{/* Deploy application controller */}}
{{ template "controller" (merge (dict "type" "application" "name" "application") $root) }}
---
{{/* Deploy microservice controllers */}}
{{ range $service := .Values.services }}
---
{{ template "controller" (merge (dict "type" "microservice" "name" $service.name) $root) }}
{{ end }}