---
apiVersion: v1
kind: Namespace
metadata:
  name: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-controller
  namespace: controller
spec:
  selector:
    matchLabels:
      app: sample-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-controller
    spec:
      containers:
        - name: server
          image: gcr.io/cs598-cloud-computing-capstone/sample-controller:0.0.1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 200Mi
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              port: 8080
              path: /status
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              port: 8080
              path: /status
---
apiVersion: v1
kind: Service
metadata:
  name: sample-controller
  namespace: controller
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8080'
spec:
  type: ClusterIP
  selector:
    app: sample-controller
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: controller-external
  namespace: controller
spec:
  type: LoadBalancer
  selector:
    app: sample-controller
  ports:
  - name: http
    port: 80
    targetPort: 8080