apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: [SERVICE_NAME]-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: [SERVICE_NAME]-deployment
  behavior:
    scaleUp:
      selectPolicy: Disabled
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
